language: node_js
node_js:
  - 4
  - 5
  - 6
  - 7
  - latest
env:
  -
  - NOCOMPRESS=1
#  - BROWSER=1
#  - BROWSER=1 NOCOMPRESS=1
script:
  - |
    if [ "x$NOCOMPRESS" = "x1" ]; then
      npm run build
    else
      npm run build_minified
    fi

    if [ "x$BROWSER" = "x1" ]; then
      npm run test-browser
    else
      npm run test
    fi
sudo: false  # Use container-based architecture
