language: node_js
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - node

env:
  -
  - NOCOMPRESS=1
#  - BROWSER=1
#  - BROWSER=1 NOCOMPRESS=1

matrix:
  include:
    - node_js: 8
      env: ESLINT=1

script:
  - |
    if [ "x$ESLINT" = "x1" ] ; then
      # specific environment for just linting
      npm run lint
    fi

    if [ "x$NOCOMPRESS" = "x1" ]; then
      npm run build
    else
      npm run build_minified
    fi

    if [ "x$BROWSER" = "x1" ]; then
      npm run test-browser
    else
      npm run test
    fi

sudo: false  # Use container-based architecture
